In [1]:
import scipy.stats
from scipy.stats import ttest_1samp

In [2]:
from statsmodels.stats.weightstats import ztest as ztest
import numpy as np

# | Z-test

data = population ,assume mean

In [3]:
data = [88,92,94,94,96,97,97,99,99,99,105,109,109,109,110,112,112,113,114,115]
pop_mean = np.array(data).mean()
pop_mean

103.15

In [4]:
# 4th cell

zscore,z_p_val= ztest(data, value = 103)#<---200 is a assume value check whether it is near to population_mean or not(103.15)
zscore, z_p_val

(0.07915681848532667, 0.9369078906275168)

In [5]:
if z_p_val<=0.05:
    print("Reject NULL: Assume mean value 200  is differnt than the population mean" )
else:
    print("Accept NULL no diff")

Accept NULL no diff


In [6]:
zscore,p_val= ztest(data, value = pop_mean)
p_val

1.0

In [7]:
if p_val<=0.05:
    print("Reject NULL   diff")
else:
    print("Accept NULL no diff")

Accept NULL no diff


## p_value is greater than 0.05 hence accept NULL hypothesis (there is NO diff. between our assume value and actual population mean value)

# | T-test

data = sample, assume mean

In [8]:
## t -test

ages =  [ 10, 20, 35, 50, 28, 40 ,55, 18, 16, 55, 30, 25, 43, 18, 30, 28, 14, 24, 16, 17, 32, 35, 26, 27, 65, 18, 43, 23, 21, 20, 19, 70]
population_mean = np.array(ages).mean()
print("Actual mean value: ",population_mean)

Actual mean value:  30.34375


In [9]:
sample_size = 10                             #<-- 10 number of values
sample = np.random.choice(ages, sample_size) 
sample

array([16, 55, 30, 35, 10, 55, 30, 26, 35, 30])

In [10]:
_,p=ttest_1samp(sample,  26)         #<--- 35 is a assume value check whether it is near to population_mean or not
p#<<<--- T-test

0.20615798720529208

In [11]:
if p<=0.05:
    print("Reject NULL   diff")
else:
    print("Accept NULL no diff")

Accept NULL no diff


## p value is less than 0.05 hence reject NULL hypothesis(there is differnce)

In [13]:
_,P_value = ttest_1samp(sample, population_mean)  #<---- exact same value population_mean
P_value

0.692861545158742

In [15]:
if P_value<=0.05:
    print("Reject NULL   diff")
else:
    print("Accept NULL no diff")

Accept NULL no diff


## p_value is greater than 0.05 hence accept NULL hypothesis (there is NO diff. between our assume value and actual population mean value)

In [16]:
ttest_1samp(sample, 26)

Ttest_1sampResult(statistic=1.3625002584520989, pvalue=0.20615798720529208)

# 2nd example

ages of the college students (population)

1) class students mean of all the ages

In [17]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math

In [18]:
np.random.seed(6)
school_ages = stats.poisson.rvs(loc=18, mu=35, size=1500)
classA_ages = stats.poisson.rvs(loc=18, mu=30, size=60)

In [19]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [20]:
classA_ages 

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [21]:
classA_ages.mean()

46.9

In [22]:
_,p_value = ttest_1samp(classA_ages, school_ages.mean())
p_value

1.139027071016194e-13

In [23]:
school_ages.mean()

53.303333333333335

In [24]:
if p_value<=0.05:
    print("Reject H0")
else:
    print("Accept H0")

Reject H0
